### ISSUE TITLE
Create a Wireframe

### ISSUE THREAD

**Issue by pengwen514** [TeamRead/Read-a-lot#1]
Create a brief wireframe to follow project mvp guidelines

**Comment by Yassin-Aru** [comment]
is this open for contributions or not ?

**Comment by pengwen514** [comment]
![1](https://github.com/TeamRead/Read-a-lot/assets/129791681/ac93ed2e-40b6-4aa0-8a69-b52c62855fea)
![2](https://github.com/TeamRead/Read-a-lot/assets/129791681/b17c3e14-c543-4ca2-9216-014bc2582c9a)
